CREATE TABLE PROPRIETARIO(
ID_PROPRIETARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(15) UNIQUE NOT NULL,
        SEXO CHAR(1) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
        EMAIL VARCHAR(50)       
);

INSERT INTO PROPRIETARIO VALUES(NULL,'RICARDO SILVA','45365178909','M','1982-08-13','ricardo.silva@hotmail.com');
INSERT INTO PROPRIETARIO VALUES(NULL,'AMANDA LIMA','09136517890','F','2000-05-29','amanda.lima@hotmail.com');
INSERT INTO PROPRIETARIO VALUES(NULL,'SOFIA PRADO','55365198909','F','1980-03-05','soprado@gmail.com');
INSERT INTO PROPRIETARIO VALUES(NULL,'MARIO PONTES','45365188909','M','1997-09-13','mariopontes@hotmail.com');


CREATE TABLE TELEFONE(
	ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
	ID_PROPRIETARIO INT
);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_PROPRIETARIO_TELEFONE
FOREIGN KEY(ID_PROPRIETARIO) REFERENCES PROPRIETARIO(ID_PROPRIETARIO);


INSERT INTO TELEFONE VALUES(NULL,'CEL','(11)93487-6606','3');
INSERT INTO TELEFONE VALUES(NULL,'CEL','(11)93487-6606','1');
INSERT INTO TELEFONE VALUES(NULL,'RES','(11)4524-0206','4');
INSERT INTO TELEFONE VALUES(NULL,'COM','(19)3387-6606','2');

CREATE TABLE ENDERECO(
	ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT, 
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_PROPRIETARIO INT UNIQUE
);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_PROPRIETARIO_ENDERECO
FOREIGN KEY(ID_PROPRIETARIO) REFERENCES PROPRIETARIO(ID_PROPRIETARIO);

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);


CREATE TABLE ESPECIE(
	ID_ESPECIE INT PRIMARY KEY AUTO_INCREMENT, 
	NOME VARCHAR(50) NOT NULL
);

INSERT INTO ESPECIE VALUES(NULL,'CACHORRO');
INSERT INTO ESPECIE VALUES(NULL,'GATO');
INSERT INTO ESPECIE VALUES(NULL,'CAVALO');
INSERT INTO ESPECIE VALUES(NULL,'PORCO DA INDIA');



CREATE TABLE RACA(
	ID_RACA INT PRIMARY KEY AUTO_INCREMENT, 
	NOME VARCHAR(50) NOT NULL,
        ID_ESPECIE INT
);

ALTER TABLE RACA ADD CONSTRAINT FK_ESPECIE_RACA
FOREIGN KEY(ID_ESPECIE) REFERENCES ESPECIE(ID_ESPECIE);


INSERT INTO RACA VALUES(NULL,'LHASA APSO','1');
INSERT INTO RACA VALUES(NULL,'MALTES','1');
INSERT INTO RACA VALUES(NULL,'MALAMUTE DO ALASKA','1');
INSERT INTO RACA VALUES(NULL,'PERSA','2');
INSERT INTO RACA VALUES(NULL,'ANGORA','2');


CREATE TABLE ANIMAL(
	ID_ANIMAL INT PRIMARY KEY AUTO_INCREMENT, 
	NOME VARCHAR(50) NOT NULL,
        DATA_NASCIMENTO DATE NOT NULL,
        SEXO CHAR(1) NOT NULL,
        COR VARCHAR(50) NOT NULL,
        ID_PROPRIETARIO INT,
        ID_RACA INT
);


ALTER TABLE ANIMAL ADD CONSTRAINT FK_PROPRIETARIO_ANIMAL
FOREIGN KEY(ID_PROPRIETARIO) REFERENCES PROPRIETARIO(ID_PROPRIETARIO);

ALTER TABLE ANIMAL ADD CONSTRAINT FK_RACA_ANIMAL
FOREIGN KEY(ID_RACA) REFERENCES RACA(ID_RACA);

INSERT INTO ANIMAL VALUES(NULL,'LAILA','2012-08-12','F','BRANCO E MARROM','2','1');
INSERT INTO ANIMAL VALUES(NULL,'PANDORA','2012-08-12','F','BRANCO E PRETO','4','3');
INSERT INTO ANIMAL VALUES(NULL,'ZEUS','2012-08-12','F','BRANCO E BEGE','3','2');
INSERT INTO ANIMAL VALUES(NULL,'MIA','2012-08-12','F','BRANCO','2','4');


CREATE TABLE CARGO(
	ID_CARGO INT PRIMARY KEY AUTO_INCREMENT, 
	NOME VARCHAR(50) NOT NULL
);

INSERT INTO CARGO VALUES(NULL,'ADMINISTRACAO');
INSERT INTO CARGO VALUES(NULL,'RECEPCIONISTA');
INSERT INTO CARGO VALUES(NULL,'VETERINARIO');
INSERT INTO CARGO VALUES(NULL,'GERENCIA');

CREATE TABLE FUNCIONARIO(
ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(15) UNIQUE NOT NULL,
        SEXO CHAR(1) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
        EMAIL VARCHAR(50),  
        ID_CARGO INT UNIQUE     
);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_CARGO_FUNCIONARIO
FOREIGN KEY(ID_CARGO) REFERENCES CARGO(ID_CARGO);

ALTER TABLE FUNCIONARIO DROP INDEX ID_CARGO_3




INSERT INTO FUNCIONARIO VALUES(NULL,'ALVARO ALMEIDA','6517657890','M','1982-08-13','ricardo.silva@hotmail.com','3');
INSERT INTO FUNCIONARIO VALUES(NULL,'NICOLE SANTOS','78909517890','F','2000-05-29','amanda.lima@hotmail.com','1');
INSERT INTO FUNCIONARIO VALUES(NULL,'LUCIA DELFINE','45365178909','F','1980-03-05','soprado@gmail.com','2');
INSERT INTO FUNCIONARIO VALUES(NULL,'PAULO FRARE','85365178979','M','1997-09-13','mariopontes@hotmail.com','4');



CREATE TABLE ESPECIALIDADE(
	ID_ESPECIALIDADE INT PRIMARY KEY AUTO_INCREMENT, 
	NOME VARCHAR(50) NOT NULL
);


INSERT INTO ESPECIALIDADE VALUES(NULL,'CLINICO GERAL');
INSERT INTO ESPECIALIDADE VALUES(NULL,'ORTOPEDIA');
INSERT INTO ESPECIALIDADE VALUES(NULL,'ENDOCRINOLOGIA');


CREATE TABLE VETERINARIO(
	ID_VETERINARIO INT PRIMARY KEY AUTO_INCREMENT, 
	NUM_CRMV VARCHAR(50) NOT NULL,
        DATAINICIO_CRMV DATE NOT NULL,  
        DATAFIM_CRMV DATE NOT NULL,
        ID_FUNCIONARIO INT,
        ID_ESPECIALIDADE INT
             
);

ALTER TABLE VETERINARIO ADD CONSTRAINT FK_FUNCIONARIO_VET
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO);

ALTER TABLE VETERINARIO ADD CONSTRAINT FK_ESPECIALIDADE_VET
FOREIGN KEY(ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE);


INSERT INTO VETERINARIO VALUES(NULL,'18587','2020-08-13','2024-07-04','1','3');
INSERT INTO VETERINARIO VALUES(NULL,'18587','2020-08-24','2023-05-10','2','2');



CREATE TABLE CONSULTAS(
	ID_CONSULTA INT PRIMARY KEY AUTO_INCREMENT, 
	DATA_HORA_CONSULTA DATETIME,
    ID_PROPRIETARIO INT,
        ID_ANIMAL INT,
        ID_VETERINARIO INT
             
);

ALTER TABLE CONSULTAS ADD CONSTRAINT FK_ANIMAL_CONSULTA
FOREIGN KEY(ID_ANIMAL) REFERENCES ANIMAL(ID_ANIMAL);

ALTER TABLE CONSULTAS ADD CONSTRAINT FK_VET_CONSULTA
FOREIGN KEY(ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO);

ALTER TABLE CONSULTAS ADD CONSTRAINT FK_PROPRIETARIO_CONSULTA
FOREIGN KEY(ID_PROPRIETARIO) REFERENCES PROPRIETARIO(ID_PROPRIETARIO);


INSERT INTO CONSULTAS VALUES(NULL,'2021-11-19 13:30:00','1','1','2');
